short_name = "pixel"
name = "Pixel Engine"
major = 4
minor = 4
patch = 0
pixel_major = 0
pixel_minor = 1
pixel_patch = 0
status = "dev"
module_config = ""
website = "https://godotengine.org"
docs = "latest"
