#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import default_theme_builders

env.add_source_files(env.scene_sources, ["theme_db.cpp", "theme_owner.cpp"])

if env.pixel_engine:
    env.add_source_files(env.scene_sources, "pixel_default_theme.cpp")
else:
    env.add_source_files(env.scene_sources, "default_theme.cpp")

SConscript("icons/SCsub")

env.Depends("#scene/theme/default_font.gen.h", "#thirdparty/fonts/Cantarell_Regular.woff2")
env.CommandNoCache(
    "#scene/theme/default_font.gen.h",
    "#thirdparty/fonts/Cantarell_Regular.woff2",
    env.Run(default_theme_builders.make_fonts_header),
)
