#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.scene_sources, "*.cpp")

if not env.pixel_engine:
	env.add_source_files(env.scene_sources, "graph/*.cpp")
