#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if not env["disable_3d"]:
    env.add_source_files(env.scene_sources, "*.cpp")

    if not env["disable_physics"]:
        SConscript("physics/SCsub")

    if not env["disable_navigation"]:
        SConscript("navigation/SCsub")
